name: Node.js Current LTS macOS and Windows CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm test
